### PR TITLE
[User Profile] [Web] Use DE instead of KDE

### PR DESCRIPTION
**Pull request by zombieJ**
Front end fix for issue-#10

### CODE REVIEW

**Comment by haoch** [comment]
@chaitaligupta please help review is what expected.

**Comment by haoch** [comment]
@zombieJ let merge after @chaitaligupta reviewed.

**Comment by chaitaligupta** [comment]
Reviews, looks good to me. please merge

**Comment by yonzhang** [comment]
merge as Chaitali has reviewed

**Pull request merged**
